import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = process.env.BASE || 'http://127.0.0.1:9301';
const dir = readdirSync('/opt/pw-browsers').find((d) => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1200, height: 800 } });
p.on('pageerror', (e) => console.log('  ECCEZIONE:', String(e.message).slice(0, 140)));
await p.goto(base + '/chiosco/', { waitUntil: 'networkidle' });
await p.fill('#u', 'gestore'); await p.fill('#p', 'sim'); await p.click('#loginBtn');
await p.waitForTimeout(2200);
await p.evaluate(() => { const t = document.querySelector('#tabs [data-v="menu"]'); if (t) t.click(); });
await p.waitForTimeout(2500);
const conta = async (sel) => p.evaluate((s) => document.querySelectorAll(s).length, sel);
console.log('pannelli comprimibili  :', await conta('#view .panel[data-fold]'));
console.log('barra Comprimi tutto   :', await p.evaluate(() => !!document.querySelector('.foldbar')));
console.log('pannello "Menù del chiosco" comprimibile:', await p.evaluate(() => {
  const h = [...document.querySelectorAll('#view h3')].find(x => /Men.* del chiosco/i.test(x.textContent));
  return h ? !!h.closest('.panel')?.dataset.fold : 'titolo non trovato';
}));
await p.evaluate(() => { const t = document.querySelector('#fold_tutti'); if (t) t.click(); });
await p.waitForTimeout(400);
console.log('dopo Comprimi tutto    :', await conta('#view .panel.chiuso'), 'chiusi su', await conta('#view .panel[data-fold]'));
console.log('la tabella e nascosta? :', await p.evaluate(() => { const t = document.querySelector('#view table'); return t ? getComputedStyle(t).display : 'nessuna tabella'; }));
await p.screenshot({ path: '/tmp/fold_crew.png' });
await b.close();
