import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = process.env.BASE || 'http://127.0.0.1:9993';
const dir = readdirSync('/opt/pw-browsers').find((d) => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 430, height: 900 }, deviceScaleFactor: 2 });
p.on('pageerror', (e) => console.log('  ECCEZIONE:', String(e.message).slice(0, 160)));
p.on('console', (m) => { if (m.type() === 'error') console.log('  console:', m.text().slice(0, 120)); });
await p.goto(base + '/', { waitUntil: 'networkidle' });
await p.waitForTimeout(900);
await p.fill('#gate_tess', 'RB-000001-4');
await p.click('#gate_enter');
await p.waitForTimeout(2400);
await p.evaluate(() => { const x = [...document.querySelectorAll('button')].find((e) => /Ho capito/i.test(e.textContent || '')); if (x) x.click(); });
await p.waitForTimeout(600);
await p.evaluate(() => { const t = document.querySelector('[data-campi]'); if (t) t.dispatchEvent(new MouseEvent('click', { bubbles: true })); });
await p.waitForTimeout(2200);
console.log('fasce disegnate      :', await p.evaluate(() => document.querySelectorAll('.matchrow').length));
console.log('tasti "Solo io"      :', await p.evaluate(() => document.querySelectorAll('[data-prenota]').length));
console.log('tasti "Apri ai soci" :', await p.evaluate(() => document.querySelectorAll('[data-apri]').length));
console.log('testo visibile       :', (await p.evaluate(() => (document.querySelector('#ovBody') || document.body).innerText.slice(0, 220))).replace(/\n/g, ' | '));
await p.screenshot({ path: '/tmp/campi_app.png' });
await b.close();
