import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = process.env.BASE || 'http://127.0.0.1:9987';
const dir = readdirSync('/opt/pw-browsers').find((d) => d.startsWith('chromium-'));
const call = async (p, o = {}) => (await fetch(base + p, { method: o.method || 'GET', headers: { 'Content-Type': 'application/json', ...(o.token ? { Authorization: 'Bearer ' + o.token } : {}) }, body: o.body ? JSON.stringify(o.body) : undefined })).json();
const { token } = await call('/api/admin/login', { method: 'POST', body: { username: 'gestore', password: 'sim' } });
await call('/api/admin/operatori', { method: 'POST', token, body: { username: 'tennis2', password: 'tennis2-123', ruolo: 'staff', permessi: ['tennis_campi'] } });
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1100, height: 800 }, deviceScaleFactor: 2 });
p.on('pageerror', (e) => console.log('  ECCEZIONE:', String(e.message).slice(0, 140)));
await p.goto(base + '/chiosco/', { waitUntil: 'networkidle' });
await p.fill('#u', 'tennis2'); await p.fill('#p', 'tennis2-123'); await p.click('#loginBtn');
await p.waitForTimeout(2600);
console.log('entrato?', await p.evaluate(() => document.querySelector('#app')?.style.display === 'block'));
console.log('errore mostrato:', (await p.evaluate(() => (document.querySelector('#loginMsg') || {}).textContent || '')).slice(0, 90));
console.log('tab disponibili:', await p.evaluate(() => [...document.querySelectorAll('#tabs button')].filter(b2 => b2.style.display !== 'none').map(b2 => b2.textContent.trim()).join(' · ')));
console.log('listino visibile?', await p.evaluate(() => /Listino/.test(document.body.innerText)));
console.log('incassi visibili?', await p.evaluate(() => /Incassato/.test(document.body.innerText)));
await p.screenshot({ path: '/tmp/delegato.png', fullPage: true });
await b.close();
