import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base='http://127.0.0.1:5980';
const dir = readdirSync('/opt/pw-browsers').find(d=>d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath:`/opt/pw-browsers/${dir}/chrome-linux/chrome`, args:['--no-sandbox'] });
const call = async (p,o={}) => (await fetch(base+p,{method:o.method||'GET',headers:{'Content-Type':'application/json',...(o.token?{Authorization:'Bearer '+o.token}:{})},body:o.body?JSON.stringify(o.body):undefined})).json();
const tk = (await call('/api/admin/login',{method:'POST',body:{username:'gestore',password:'shot-admin'}})).token;
const oggi = new Date().toISOString().slice(0,10);
const f = await call('/api/admin/film',{method:'POST',token:tk,body:{titolo:'Jazz & Cocktail — live',regia:'trio'}});
await call('/api/admin/proiezioni',{method:'POST',token:tk,body:{film_id:f.id,data:oggi,ora:'21:30'}});
// una cena al garden porta con sé i posti davanti al palco
await call('/api/garden/prenota',{method:'POST',body:{tessera_code:'BR-2026-0001',data:oggi,turno:'20:00',persone:4}});
await call('/api/garden/prenota',{method:'POST',body:{tessera_code:'BR-2026-0002',data:oggi,turno:'20:00',persone:2}});
const p = await b.newPage({ viewport:{width:1100,height:1100} });
await p.goto(base+'/chiosco/',{waitUntil:'networkidle'});
await p.fill('#u','gestore'); await p.fill('#p','shot-admin'); await p.click('#loginBtn'); await p.waitForTimeout(1800);
await p.selectOption('#zonaSwitch','cinema'); await p.waitForTimeout(1500);
await p.click('#tabs [data-v="pianta"]'); await p.waitForTimeout(2200);
await p.screenshot({path:'/tmp/stage_pianta.png', fullPage:true});
await b.close(); console.log('ok');
