import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base='http://127.0.0.1:5960';
const dir = readdirSync('/opt/pw-browsers').find(d=>d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath:`/opt/pw-browsers/${dir}/chrome-linux/chrome`, args:['--no-sandbox'] });
const call = async (p,o={}) => (await fetch(base+p,{method:o.method||'GET',headers:{'Content-Type':'application/json',...(o.token?{Authorization:'Bearer '+o.token}:{})},body:o.body?JSON.stringify(o.body):undefined})).json();
const tk = (await call('/api/admin/login',{method:'POST',body:{username:'gestore',password:'shot-admin'}})).token;
const oggi = new Date().toISOString().slice(0,10);
const turni = (await call('/api/carta/turni?data='+oggi)).turni;
await call('/api/carta/prenota',{method:'POST',body:{tessera_code:'BR-2026-0001',data:oggi,turno:turni[0].turno,persone:4}});
await call('/api/carta/prenota',{method:'POST',body:{tessera_code:'BR-2026-0002',data:oggi,turno:turni[0].turno,persone:2}});
const sala = await call('/api/admin/carta/sala?turno='+encodeURIComponent(turni[0].turno),{token:tk});
const giochi = await call('/api/admin/cdc/giochi',{token:tk});
await call('/api/admin/cdc/prestiti',{method:'POST',token:tk,body:{gioco_id:giochi[0].id,gioco_nome:giochi[0].nome,giocatore:'Ercole',ora_inizio:'17:10',tavolo:sala.tavoli.find(t=>!t.libero)?.numero||1}});
await call('/api/admin/cdc/prestiti',{method:'POST',token:tk,body:{gioco_id:giochi[1].id,gioco_nome:giochi[1].nome,giocatore:'Giulia',ora_inizio:'17:20',tavolo:sala.tavoli.filter(t=>!t.libero)[1]?.numero||2}});
const m = await b.newPage({ viewport:{width:430,height:940}, isMobile:true, hasTouch:true });
await m.goto(base+'/chiosco/',{waitUntil:'networkidle'});
await m.fill('#u','gestore'); await m.fill('#p','shot-admin'); await m.click('#loginBtn'); await m.waitForTimeout(1800);
await m.selectOption('#zonaSwitch','cdc'); await m.waitForTimeout(2200);
await m.screenshot({path:'/tmp/carta_crew.png', fullPage:true});
await b.close(); console.log('ok');
