import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base='http://127.0.0.1:5970';
const dir = readdirSync('/opt/pw-browsers').find(d=>d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath:`/opt/pw-browsers/${dir}/chrome-linux/chrome`, args:['--no-sandbox'] });
const call = async (p,o={}) => (await fetch(base+p,{method:o.method||'GET',headers:{'Content-Type':'application/json',...(o.token?{Authorization:'Bearer '+o.token}:{})},body:o.body?JSON.stringify(o.body):undefined})).json();
const tk = (await call('/api/admin/login',{method:'POST',body:{username:'gestore',password:'shot-admin'}})).token;
const f = await call('/api/admin/film',{method:'POST',token:tk,body:{titolo:'Nuovo Cinema Paradiso',regia:'Tornatore',anno:1988,durata_min:155}});
const gg = new Date(Date.now()+2*864e5).toISOString().slice(0,10);
const pr = await call('/api/admin/proiezioni',{method:'POST',token:tk,body:{film_id:f.id,data:gg,ora:'21:30'}});
for (const t of ['BR-2026-0001','BR-2026-0002']) await call(`/api/cinema/${pr.id}/prenota`,{method:'POST',body:{tessera_code:t,persone:2}});
const oggi = new Date().toISOString().slice(0,10);
await call('/api/admin/sala',{method:'POST',token:tk,body:{data:oggi,ora_inizio:'09:00',ora_fine:'11:00',scopo:'riunione',titolo:'Assemblea condominiale',richiedente:'CdA',persone:10}});
const m = await b.newPage({ viewport:{width:430,height:940}, isMobile:true, hasTouch:true });
await m.goto(base+'/chiosco/',{waitUntil:'networkidle'});
await m.fill('#u','gestore'); await m.fill('#p','shot-admin'); await m.click('#loginBtn'); await m.waitForTimeout(1800);
await m.selectOption('#zonaSwitch','cinema'); await m.waitForTimeout(2000);
await m.screenshot({path:'/tmp/crew_cinema.png', fullPage:true});
await m.selectOption('#zonaSwitch','cdc'); await m.waitForTimeout(1500);
await m.click('#tabs [data-v="pianta"]').catch(()=>{});
await m.close();
const p = await b.newPage({ viewport:{width:1280,height:1000} });
await p.goto(base+'/admin/',{waitUntil:'networkidle'});
await p.fill('#u','gestore'); await p.fill('#p','shot-admin'); await p.click('#loginBtn'); await p.waitForTimeout(1800);
await p.click('button[data-v="sala"]'); await p.waitForTimeout(1500);
await p.screenshot({path:'/tmp/admin_sala.png', fullPage:true});
await b.close(); console.log('ok');
