import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base='http://127.0.0.1:5994';
const dir = readdirSync('/opt/pw-browsers').find(d=>d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath:`/opt/pw-browsers/${dir}/chrome-linux/chrome`, args:['--no-sandbox'] });
const call = async (p,o={}) => (await fetch(base+p,{method:o.method||'GET',headers:{'Content-Type':'application/json',...(o.token?{Authorization:'Bearer '+o.token}:{})},body:o.body?JSON.stringify(o.body):undefined})).json();
const tk = (await call('/api/admin/login',{method:'POST',body:{username:'gestore',password:'shot-admin'}})).token;
const oggi = new Date().toISOString().slice(0,10);
const lun = (n=0) => { const d=new Date(Date.now()+n*864e5); d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7)); return d.toISOString().slice(0,10); };
const piu = (iso,g) => new Date(new Date(iso+'T12:00:00Z').getTime()+g*864e5).toISOString().slice(0,10);
const i1 = lun(0);
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Pilates',istruttore:'Anna R.',data_inizio:i1,data_fine:piu(i1,13),giorni:[1,3,5],ora:'18:00',durata_min:50,posti_max:20,min_iscritti:10,prezzo:12}});
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Yoga all’alba',istruttore:'Marco L.',data_inizio:i1,data_fine:piu(i1,13),giorni:[2,4,6],ora:'07:00',durata_min:60,posti_max:15,min_iscritti:10,prezzo:15}});
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Zumba',istruttore:'Carla D.',data_inizio:i1,data_fine:piu(i1,13),giorni:[5],ora:'19:30',durata_min:50,posti_max:30,min_iscritti:10,prezzo:10}});
// un po' di vita per il cruscotto
const menu = await call('/api/menu?zona=garden');
await call('/api/self-order',{method:'POST',body:{punto:'Bussola Garden',tavolo:'3',righe:[{menu_id:menu[0].id,qta:2}]}});
await call('/api/self-order',{method:'POST',body:{punto:'Bussola Bar',tavolo:'1',righe:[{menu_id:menu[0].id,qta:1}]}});
await call('/api/garden/prenota',{method:'POST',body:{tessera_code:'BR-2026-0001',data:oggi,turno:'20:00',persone:4}});
await call('/api/admin/magazzino',{method:'POST',token:tk,body:{nome:'Tovaglioli',zona:'comune',unita:'pz',giacenza:5,punto_riordino:50}});
const sed = await call('/api/admin/fitness/sedute',{token:tk});
if (sed[0]) for (const t of ['BR-2026-0001','BR-2026-0002']) await call(`/api/fitness/sedute/${sed[0].id}/prenota`,{method:'POST',body:{tessera_code:t}});
const p = await b.newPage({ viewport:{width:1280,height:1100} });
await p.goto(base+'/admin/',{waitUntil:'networkidle'});
await p.fill('#u','gestore'); await p.fill('#p','shot-admin'); await p.click('#loginBtn'); await p.waitForTimeout(2000);
await p.screenshot({path:'/tmp/cruscotto.png', fullPage:true});
await p.click('button[data-v="fitness"]'); await p.waitForTimeout(1800);
await p.screenshot({path:'/tmp/fit_cal.png', fullPage:true});
await b.close(); console.log('ok');
