import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = process.env.BASE || 'http://127.0.0.1:9975';
const dir = readdirSync('/opt/pw-browsers').find((d) => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 430, height: 950 }, deviceScaleFactor: 2 });
p.on('pageerror', (e) => console.log('  ECCEZIONE:', String(e.message).slice(0, 140)));
await p.goto(base + '/', { waitUntil: 'networkidle' });
await p.waitForTimeout(900);
await p.evaluate(() => { const b2 = document.querySelector('[data-gatelang="en"]'); if (b2) b2.click(); });
await p.waitForTimeout(400);
await p.fill('#gate_tess', 'RB-000001-4'); await p.click('#gate_enter');
await p.waitForTimeout(2400);
await p.evaluate(() => { const x = [...document.querySelectorAll('button')].find((e) => /Got it|Ho capito/i.test(e.textContent || '')); if (x) x.click(); });
await p.waitForTimeout(600);
await p.evaluate(() => { const t = [...document.querySelectorAll('.tab')].find(x => /Guide|Guida/i.test(x.textContent)); if (t) t.click(); });
await p.waitForTimeout(1800);
const txt = await p.evaluate(() => document.body.innerText);
console.log('chip della legenda:', await p.evaluate(() => [...document.querySelectorAll('.chip')].map(c => c.textContent.trim()).join(' | ')));
console.log('tipi dal server   :', await p.evaluate(() => (window.state?.data?.rifiuti?.tipi || []).map(t => t.nome).join(' | ')));
console.log('lingua corrente   :', await p.evaluate(() => window.state?.lang));
await p.screenshot({ path: '/tmp/guida_chip.png', fullPage: true });
await b.close();
