import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = 'http://127.0.0.1:5000';
const dir = readdirSync('/opt/pw-browsers').find(d => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const call = async (p, o = {}) => (await fetch(base + p, { method: o.method || 'GET', headers: { 'Content-Type': 'application/json', ...(o.token ? { Authorization: 'Bearer ' + o.token } : {}) }, body: o.body ? JSON.stringify(o.body) : undefined })).json();
const tk = (await call('/api/admin/login', { method: 'POST', body: { username: 'gestore', password: 'shot-admin' } })).token;
await call('/api/admin/eventi', { method: 'POST', token: tk, body: { giorno: 'ven', titolo: 'Serata dei Clan', sottotitolo: 'Karaoke', tipologia: 'contest', costo_tipo: 'consumazione', consumazione: '1 consumazione obbligatoria' } });
await call('/api/admin/eventi', { method: 'POST', token: tk, body: { giorno: 'gio', titolo: 'Jazz & Cocktail', tipologia: 'live', costo_tipo: 'prezzo', prezzo: 12 } });
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } });
await p.goto(base + '/admin/', { waitUntil: 'networkidle' });
await p.fill('#u', 'gestore'); await p.fill('#p', 'shot-admin'); await p.click('#loginBtn'); await p.waitForTimeout(1800);
await p.click('text=Regole & parametri'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/par.png', fullPage: true });
await p.click('#menu [data-v="eventi"]').catch(async () => await p.click('button[data-v="eventi"]')); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/eventi.png', fullPage: true });
await b.close();
console.log('ok');
