import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = process.env.BASE || 'http://127.0.0.1:9981';
const dir = readdirSync('/opt/pw-browsers').find((d) => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 430, height: 900 }, deviceScaleFactor: 2 });
p.on('pageerror', (e) => console.log('  ECCEZIONE:', String(e.message).slice(0, 140)));
await p.goto(base + '/', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
console.log('selettore lingua nel gate:', await p.evaluate(() => document.querySelectorAll('[data-gatelang]').length));
await p.screenshot({ path: '/tmp/gate_it.png' });
await p.evaluate(() => { const b2 = document.querySelector('[data-gatelang="de"]'); if (b2) b2.click(); });
await p.waitForTimeout(600);
console.log('dopo il tedesco →', await p.evaluate(() => (document.querySelector('#gate_t1') || {}).textContent + ' · ' + (document.querySelector('#gate_t3') || {}).textContent));
await p.screenshot({ path: '/tmp/gate_de.png' });
// e la registrazione parla la stessa lingua?
await p.evaluate(() => { const r = document.querySelector('#gate_register'); if (r) r.click(); });
await p.waitForTimeout(1200);
await p.screenshot({ path: '/tmp/gate_reg.png' });
await b.close();
console.log('ok');
