import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = 'http://127.0.0.1:5300';
const dir = readdirSync('/opt/pw-browsers').find(d => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } });
await p.goto(base + '/admin/', { waitUntil: 'networkidle' });
await p.fill('#u', 'gestore'); await p.fill('#p', 'x'); await p.click('#loginBtn'); await p.waitForTimeout(1800);
await p.click('#menu [data-v="tabellone"]').catch(async () => await p.click('button[data-v="tabellone"]'));
await p.waitForTimeout(1800);
await p.screenshot({ path: '/tmp/tornei_avviso.png', fullPage: true });
await b.close(); console.log('ok');
