import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base = 'http://127.0.0.1:5700';
const dir = readdirSync('/opt/pw-browsers').find(d => d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath: `/opt/pw-browsers/${dir}/chrome-linux/chrome`, args: ['--no-sandbox'] });
const call = async (p,o={}) => (await fetch(base+p,{method:o.method||'GET',headers:{'Content-Type':'application/json',...(o.token?{Authorization:'Bearer '+o.token}:{})},body:o.body?JSON.stringify(o.body):undefined})).json();
const tk = (await call('/api/admin/login',{method:'POST',body:{username:'gestore',password:'shot-admin'}})).token;
const lun = (n) => { const d=new Date(Date.now()+(2+n*7)*864e5); d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7)); return d.toISOString().slice(0,10); };
const fine = (iso,g) => new Date(new Date(iso+'T12:00:00Z').getTime()+g*864e5).toISOString().slice(0,10);
const i1 = lun(0);
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Pilates',istruttore:'Anna Rizzo',descrizione:'Postura e respiro, livello base',data_inizio:i1,data_fine:fine(i1,6),giorni:[1,3,5],ora:'09:00',durata_min:55,posti_max:18,min_iscritti:10,prezzo:12}});
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Yoga all’alba',istruttore:'Marco Li Volsi',descrizione:'Saluto al sole in riva al mare',data_inizio:i1,data_fine:fine(i1,13),giorni:[2,6],ora:'07:00',durata_min:60,posti_max:15,min_iscritti:10,prezzo:15}});
await call('/api/admin/fitness/corsi',{method:'POST',token:tk,body:{nome:'Zumba',istruttore:'Carla D.',descrizione:'Serata danzante',data_inizio:i1,data_fine:fine(i1,6),giorni:[4],ora:'19:00',durata_min:50,posti_max:30,min_iscritti:10,prezzo:10}});
const sed = await call('/api/admin/fitness/sedute',{token:tk});
const prima = sed[0];
for (const t of ['BR-2026-0001','BR-2026-0002','BR-2026-0003','BR-2026-0004']) await call(`/api/fitness/sedute/${prima.id}/prenota`,{method:'POST',body:{tessera_code:t}});
await call(`/api/admin/fitness/sedute/${sed[2].id}`,{method:'PUT',token:tk,body:{masterclass:true,prezzo:35,titolo:'Masterclass con ospite',istruttore:'Nome noto del settore',ora:sed[2].ora,posti_max:sed[2].posti_max,min_iscritti:sed[2].min_iscritti}});
const el = (await call('/api/admin/fitness/sedute',{token:tk})).find(x=>x.id===prima.id);
await call('/api/admin/fitness/prenotazioni/'+el.elenco[0].id,{method:'PUT',token:tk,body:{pagato:true}});
const p = await b.newPage({ viewport:{width:1280,height:1000} });
await p.goto(base+'/admin/',{waitUntil:'networkidle'});
await p.fill('#u','gestore'); await p.fill('#p','shot-admin'); await p.click('#loginBtn'); await p.waitForTimeout(1800);
await p.click('button[data-v="fitness"]'); await p.waitForTimeout(1800);
await p.screenshot({ path:'/tmp/fitness_admin.png', fullPage:true });
await p.close();
const m = await b.newPage({ viewport:{width:430,height:940}, isMobile:true, hasTouch:true });
await m.goto(base+'/chiosco/',{waitUntil:'networkidle'});
await m.fill('#u','gestore'); await m.fill('#p','shot-admin'); await m.click('#loginBtn'); await m.waitForTimeout(1800);
await m.selectOption('#zonaSwitch','fitness'); await m.waitForTimeout(1800);
await m.screenshot({ path:'/tmp/fitness_crew.png', fullPage:true });
await b.close(); console.log('ok');
