import { chromium } from 'playwright-core';
import { readdirSync } from 'node:fs';
const base='http://127.0.0.1:5900';
const dir = readdirSync('/opt/pw-browsers').find(d=>d.startsWith('chromium-'));
const b = await chromium.launch({ executablePath:`/opt/pw-browsers/${dir}/chrome-linux/chrome`, args:['--no-sandbox'] });
const a = await b.newPage({ viewport:{width:390,height:860}, isMobile:true, hasTouch:true });
await a.goto(base+'/',{waitUntil:'networkidle'});
await a.fill('#gate_tess','BR-2026-0001'); await a.click('#gate_enter'); await a.waitForTimeout(2200);
await a.click('text=Ho capito, inizia').catch(()=>{}); await a.waitForTimeout(800);
await a.screenshot({path:'/tmp/mq_home.png', fullPage:true});
await a.click('nav [data-t="sport"]'); await a.waitForTimeout(1200);
await a.screenshot({path:'/tmp/mq_sport.png', fullPage:true});
await a.click('nav [data-t="bussola"]'); await a.waitForTimeout(1200);
await a.screenshot({path:'/tmp/mq_guida.png', fullPage:true});
await b.close(); console.log('ok');
